#include "catch_amalgamated.hpp"
#include "Chess-Model.h"

//................................................
//.TTTTTTTTTTTEEEEEEEEEEE..SSSSSSS....STTTTTTTTT..
//.TTTTTTTTTTTEEEEEEEEEEE.ESSSSSSSS...STTTTTTTTT..
//.TTTTTTTTTTTEEEEEEEEEEE.ESSSSSSSSS..STTTTTTTTT..
//....TTTT....EEEE.......EESSS..SSSS.....TTTT.....
//....TTTT....EEEE.......EESSS...........TTTT.....
//....TTTT....EEEEEEEEEE..ESSSSSS........TTTT.....
//....TTTT....EEEEEEEEEE...SSSSSSSSS.....TTTT.....
//....TTTT....EEEEEEEEEE.....SSSSSSS.....TTTT.....
//....TTTT....EEEE..............SSSSS....TTTT.....
//....TTTT....EEEE.......EESS....SSSS....TTTT.....
//....TTTT....EEEEEEEEEEEEESSSSSSSSSS....TTTT.....
//....TTTT....EEEEEEEEEEE.ESSSSSSSSS.....TTTT.....
//....TTTT....EEEEEEEEEEE..SSSSSSSS......TTTT.....
//................................................


